CREATE DATABASE NS;
USE NS;
CREATE TABLE IF NOT EXISTS Users(
    id int NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    correo VARCHAR(50) NOT NULL,
    telefono VARCHAR(50) NOT NULL,
    PRIMARY KEY (id));
